#include "html_pages.h"

const char *CP_HTML_FORM =
    "<!doctype html>"
    "<html>"
    "<head>"
    "<meta charset='UTF-8'/>"
    "<meta name='viewport' content='width=device-width, initial-scale=1'/>"
    "<title>Wi-Fi Setup</title>"
    "<style>"
    "body {"
    "  font-family: Arial, sans-serif;"
    "  background: #f2f2f2;"
    "  display: flex;"
    "  justify-content: center;"
    "  align-items: center;"
    "  height: 100vh;"
    "  margin: 0;"
    "}"
    ".card {"
    "  background: white;"
    "  padding: 20px 25px;"
    "  border-radius: 12px;"
    "  box-shadow: 0 4px 10px rgba(0,0,0,0.1);"
    "  max-width: 350px;"
    "  width: 90%;"
    "}"
    "h3 { text-align: center; margin-bottom: 20px; }"
    "input {"
    "  width: 100%;"
    "  padding: 10px;"
    "  margin-top: 5px;"
    "  margin-bottom: 15px;"
    "  border-radius: 8px;"
    "  border: 1px solid #ccc;"
    "  font-size: 16px;"
    "}"
    "button {"
    "  width: 100%;"
    "  padding: 12px;"
    "  border: none;"
    "  background: #007aff;"
    "  color: white;"
    "  font-size: 16px;"
    "  border-radius: 8px;"
    "  cursor: pointer;"
    "}"
    "button:hover { background: #0060d1; }"
    "</style>"
    "</head>"
    "<body>"
    "<div class='card'>"
    "<h3>Wi-Fi Setup</h3>"
    "<form method='POST' action='/connect'>"
    "<label>SSID</label>"
    "<input name='ssid' required placeholder='Network name'>"
    "<label>Password</label>"
    "<div style='position:relative;'>"
    "  <input id='pw' name='pass' type='password' placeholder='Password' style='padding-right:40px;'>"
    "  <span onclick=\"togglePw()\" "
    "        style='position:absolute; right:10px; top:50%; transform:translateY(-50%); "
    "               cursor:pointer; font-size:18px; user-select:none;'>👁️</span>"
    "</div>"
    "<script>"
    "function togglePw(){"
    "  var p=document.getElementById('pw');"
    "  p.type = (p.type === 'password') ? 'text' : 'password';"
    "}"
    "</script>"
    "<button type='submit'>Connect</button>"
    "</form>"
    "</div>"
    "</body>"
    "</html>";

const char *RESP =
    "<!doctype html>"
    "<html>"
    "<head>"
    "  <meta charset='UTF-8'/>"
    "  <meta name='viewport' content='width=device-width, initial-scale=1'/>"
    "  <title>Connecting...</title>"
    "  <style>"
    "    body {"
    "      font-family: Arial, sans-serif;"
    "      background: #f5f5f5;"
    "      display: flex;"
    "      justify-content: center;"
    "      align-items: center;"
    "      height: 100vh;"
    "      margin: 0;"
    "    }"
    "    .card {"
    "      background: #ffffff;"
    "      padding: 30px 25px;"
    "      border-radius: 12px;"
    "      box-shadow: 0 4px 15px rgba(0,0,0,0.2);"
    "      text-align: center;"
    "      max-width: 350px;"
    "      width: 90%;"
    "    }"
    "    h3 { color: #007aff; margin-bottom: 20px; }"
    "    p { color: #333333; line-height: 1.5; margin: 10px 0; }"
    "    .spinner {"
    "      margin: 20px auto;"
    "      width: 40px;"
    "      height: 40px;"
    "      border: 4px solid #f3f3f3;"
    "      border-top: 4px solid #007aff;"
    "      border-radius: 50%;"
    "      animation: spin 1s linear infinite;"
    "    }"
    "    @keyframes spin {"
    "      0% { transform: rotate(0deg); }"
    "      100% { transform: rotate(360deg); }"
    "    }"
    "  </style>"
    "</head>"
    "<body>"
    "  <div class='card'>"
    "    <h3>Connecting your device to Wi-Fi...</h3>"
    "    <div class='spinner'></div>"
    "    <p>Please wait while the device connects to your network.</p>"
    "    <p>Once connected, the device LED will stay lit, indicating a successful connection.</p>"
    "  </div>"
    "</body>"
    "</html>";
